runtime: custom
service: default 
env: flex
threadsafe: true
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
network:
  session_affinity: true
automatic_scaling:
  max_num_instances: 1
env_variables:
  MONGO_URL: mongodb+srv://<dbUserName>:<dbPassword>@<dbAddress>.gcp.mongodb.net/test?retryWrites=true&w=majority
  ROOT_URL: https://www.foo.com
  MAIL_URL:
skip_files:
- ^(.*/)?\.dockerignore$
- ^(.*/)?\yarn-error.log$
- ^(.*/)?\.git$
- ^(.*/)?\.hg$
- ^(.*/)?\.svn$
- ^(.*/)?\.meteor/local$
  
